"""Ports: the interfaces the use cases depend on.

Concrete adapters (Postgres, Redis, RabbitMQ) implement these Protocols and are
injected at wiring time. The dependency arrow points inward. Protocols give us
structural typing, so an adapter satisfies a port just by having the right methods.
"""
from __future__ import annotations

from datetime import datetime, timedelta
from typing import Protocol

from app.domain.models import (
    Event,
    Order,
    Payment,
    QueueToken,
    Reservation,
    Role,
    Sector,
    User,
)


class UserRepository(Protocol):
    async def find_by_email(self, email: str) -> User | None: ...
    async def find_by_id(self, user_id: str) -> User | None: ...


class EventRepository(Protocol):
    async def list(self, cursor: str, limit: int) -> tuple[list[Event], str]: ...
    async def find_by_id(self, event_id: str) -> Event | None: ...


class SectorRepository(Protocol):
    async def list_by_event(self, event_id: str) -> list[Sector]: ...
    async def find_by_id(self, sector_id: str) -> Sector | None: ...
    # Returns True only if enough remained. The conditional UPDATE is the real
    # guarantee against overselling; the distributed lock is belt and braces.
    async def decrement_inventory(self, sector_id: str, qty: int) -> bool: ...
    async def increment_inventory(self, sector_id: str, qty: int) -> None: ...


class QueueRepository(Protocol):
    async def upsert(self, token: QueueToken) -> None: ...
    async def find(self, user_id: str, event_id: str) -> QueueToken | None: ...
    async def next_position(self, event_id: str) -> int: ...


class ReservationRepository(Protocol):
    # create raises domain.CONFLICT on a unique (user_id, idempotency_key) violation.
    async def create(self, r: Reservation) -> None: ...
    async def find_by_id(self, reservation_id: str) -> Reservation | None: ...
    async def find_by_idempotency_key(self, user_id: str, key: str) -> Reservation | None: ...
    async def update_status(self, reservation_id: str, status: str) -> None: ...
    async def find_expired(self, now: datetime, limit: int) -> list[Reservation]: ...


class OrderRepository(Protocol):
    async def create(self, o: Order) -> None: ...
    async def find_by_id(self, order_id: str) -> Order | None: ...
    async def find_by_reservation_id(self, reservation_id: str) -> Order | None: ...
    async def find_by_idempotency_key(self, user_id: str, key: str) -> Order | None: ...
    async def update_status(self, order_id: str, status: str) -> None: ...


class PaymentRepository(Protocol):
    # Idempotent by provider_ref so a replayed webhook is a no-op.
    async def upsert(self, p: Payment) -> None: ...
    async def find_by_order_id(self, order_id: str) -> Payment | None: ...


class Locker(Protocol):
    # Returns an async context manager token or None if the lock was not acquired.
    async def acquire(self, key: str, wait: timedelta): ...


class Publisher(Protocol):
    async def publish(self, topic: str, payload: bytes) -> None: ...


class RateLimiter(Protocol):
    async def allow(self, key: str, limit: int, window: timedelta) -> bool: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class IDGenerator(Protocol):
    def new_id(self) -> str: ...


class PasswordHasher(Protocol):
    def verify(self, hashed: str, plaintext: str) -> bool: ...


class TokenService(Protocol):
    def issue_access(self, user_id: str, role: Role) -> tuple[str, int]: ...
    async def issue_refresh(self, user_id: str) -> str: ...
    async def rotate(self, refresh_token: str) -> str: ...  # returns user_id; raises on reuse
    def parse_access(self, token: str) -> tuple[str, Role]: ...


class PaymentGateway(Protocol):
    async def charge(self, order_id: str) -> str: ...  # returns provider_ref
